name: Discord Push bot

on:
  # Notifie tous les push sur toutes les branches (modifie si tu veux filtrer)
  push:
    # exemples pour ignorer certaines branches ou auteurs:
    # branches-ignore:
    #   - 'dependabot/**'
  # Notifie la création de branches
  create:

permissions:
  contents: read

jobs:
  discord-push:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      CHANNEL_ID: ${{ secrets.DISCORD_PUSH_CHANNEL_ID }}
    steps:
      - name: Require secrets
        run: |
          test -n "$BOT_TOKEN" && test -n "$CHANNEL_ID" || { echo "Missing secrets"; exit 1; }

      # --- Création de branche ---
      - name: Notify on new branch
        if: ${{ github.event_name == 'create' && github.event.ref_type == 'branch' }}
        env:
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.event.ref }}
          ACTOR: ${{ github.actor }}
        run: |
          BRANCH_URL="https://github.com/${REPO}/tree/${BRANCH}"
          CONTENT=$(printf ':seedling: **New branch created**\n\nRepository: **%s**\nBranch: `%s`\nBy: **%s**\nLink: %s' "$REPO" "$BRANCH" "$ACTOR" "$BRANCH_URL")
          curl -sS -H "Authorization: Bot $BOT_TOKEN" -H "Content-Type: application/json" \
            -d "$(printf '{"content":"%s"}' "$CONTENT")" \
            https://discord.com/api/v10/channels/$CHANNEL_ID/messages >/dev/null

      # --- Push de commits ---
      - name: Notify on push
        if: ${{ github.event_name == 'push' }}
        env:
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }} # dispo nativement dans GitHub Actions
          ACTOR: ${{ github.actor }}
          COMPARE_URL: ${{ github.event.compare }}
        run: |
          # On limite l’aperçu aux 10 premiers commits pour éviter les pavés
          TOTAL=$(jq '.commits | length' "$GITHUB_EVENT_PATH")
          PREVIEW_COUNT=$(jq 'if .commits | length > 10 then 10 else .commits | length end' "$GITHUB_EVENT_PATH")
          COMMITS=$(jq -r '.commits[:10][] | "- [`\(.id[0:7])`](" + .url + ") \(.message | split("\n")[0]) — \(.author.username // .author.name)"' "$GITHUB_EVENT_PATH")

          MORE=""
          if [ "$TOTAL" -gt "$PREVIEW_COUNT" ]; then
            MORE=$(printf "\n…and %d more commits." $((TOTAL - PREVIEW_COUNT)))
          fi

          CONTENT=$(printf ':arrow_up: **Push to `%s`**\n\nRepository: **%s**\nPusher: **%s**\nCommits: **%d**\nCompare: %s\n\n%s%s' \
            "$BRANCH" "$REPO" "$ACTOR" "$TOTAL" "$COMPARE_URL" "$COMMITS" "$MORE")

          curl -sS -H "Authorization: Bot $BOT_TOKEN" -H "Content-Type: application/json" \
            -d "$(printf '{"content":"%s"}' "$CONTENT")" \
            https://discord.com/api/v10/channels/$CHANNEL_ID/messages >/dev/null
